avahi_dns_handler.c
void resolve_callback(AvahiServiceResolver *r, AvahiIfIndex interface, AvahiProtocol protocol, AvahiResolverEvent event, const char *name, const char *type, const char *domain, const char *host_name, const AvahiAddress *address, uint16_t port, AvahiStringList *txt, AvahiLookupResultFlags flags, void *userdata)
Called whenever a service has been resolved successfully or timed out. simple_poll_reader.c in libavahi API userdata An avahi_callback_params pointer containing relevant data.
References list_foreach_entry, list_push, rfid_server_info::lock, rfid_server_info::name, rfid_server_info::port, client_config::servers, rfid_server_info::stable, rfid_server_info::url.
Referenced by browse_callback.
void browse_callback(AvahiServiceBrowser *b, AvahiIfIndex interface, AvahiProtocol protocol, AvahiBrowserEvent event, const char *name, const char *type, const char *domain, AvahiLookupResultFlags flags, void *userdata)
Called whenever a new services becomes available on the LAN or is removed from the LAN. simple_poll_reader.c in libavahi API userdata An avahi_callback_params pointer containing relevant data.
References avahi_callback_params::client, list_foreach_entry, list_remove, rfid_server_info::name, avahi_callback_params::poll, resolve_callback, client_config::servers, rfid_server_info::stable.
Referenced by avahi_function.
void client_callback(AvahiClient *c, AvahiClientState state, void *userdata)
Called whenever the client or server state changes. c The current client. state The current state. userdata Relevant data, including configuration settings.
Referenced by avahi_function.
void* avahi_function(void *args)
mDNS handling loop which looks for RFIDentify servers. Look for avahi_dns_handler.c
PThread. Initializes an mDNS Avahi service, and listens for relevant services. Updates the server info configuration as necessary. args struct client_config, Relevant configuration settings. Should not return, if so, error.
References browse_callback, avahi_callback_params::client, client_callback, avahi_callback_params::config, avahi_callback_params::poll.