config.c
DEBUG
Whether to print out debug messages to STDOUT.
Referenced by debug.
WARN
Whether to print out warning messages to STDOUT.
Referenced by warn.
void warn(const char *warning)
Prints the given warning message to STDOUT if defined. warning The message to print.
References WARN.
Referenced by config_get, config_get_all.
void debug(const char *debug)
Prints the given debug message to STDOUT if defined. debug The message to print.
References DEBUG.
char* config_get(const char *filename, const char *key)
Get a value from a configuration file identified by a filename.
Given a file, and key, return the first matching config value. filename The config file. key The key of which the value to find. A newly allocated string, or NULL on failure.
References config_get_all, list_destroy, list_is_empty, list_pop, warn.
Referenced by read_config.
list* config_get_all(const char *filename, const char *key)
Gets all relevant values from a configuration file identifed by a filename.
Given a filename and key, return all matching config values. filename The filename of the configuration file. key The key to which to match configuration definitions. A newly allocated list of newly allocated values, or NULL on failure.
References list_append, list_create, warn.
Referenced by config_get, read_config_servers.