list.h
list_foreach
l list *, the list to enumerate t list *, a temporary list
list_foreach_entry
l list *l - the list to enumerate t list *t - a temporary list type the type of the entry e - entry of type TYPE
Referenced by browse_callback, read_config_servers, reader_handle_tag, resolve_callback.
ENOTFND
typedef struct list list
standardization:a list ends with a cell that looks like:+---+---+ --->|v|0| +---+---+ and empty list then looks like:+---+---+ |0|0| +---+---+ it should look like this:0 but this doesnt work, because we would need to be able to modify the pointers but of course they are passed by value...so this implementation needs to be careful on edge cases, checking when there are fewer than 2 elements and whatnot
typedef list list_t
list* list_create()
A newly allocated list, or NULL on failure
Referenced by config_get_all, list_cons, list_push, null_list, read_config_servers, reader_function, reader_poll_loop, string_split.
void list_atom_destroy(list *l)
inverse of list_create() does not free contents
Referenced by list_destroy, list_destroy_deep, list_pop, list_remove.
void list_destroy(list *l)
list_atom_destroy() chained together across an entire list. currently recursive, so probs not a good function for large lists... although i heard GCC can optimize tail recursion, so this may be fine
References list_atom_destroy, list_cdr, list_destroy, list_is_null.
Referenced by config_get, list_destroy, list_filter, read_config_servers, reader_function, reader_poll_loop.
void list_destroy_deep(list *l)
like list_destroy() but calls free on each car.
References list_atom_destroy, list_car, list_cdr, list_destroy_deep, list_is_empty, list_is_null.
Referenced by list_destroy_deep, string_split.
void* list_car(list *l)
l a list. The car of the list.
Referenced by list_append, list_array, list_destroy_deep, list_filter, list_index_of_int, list_index_of_str, list_is_empty, list_map, list_nth, list_pop, list_push, list_remove, list_size, string_join.
void* list_cdr(list *l)
a list The cdr of the list.
Referenced by list_append, list_array, list_destroy, list_destroy_deep, list_filter, list_index_of_int, list_index_of_str, list_is_empty, list_map, list_nth, list_nth_atom, list_pop, list_push, list_remove, list_reverse, list_size, string_join.
void list_set_car(list *l, void *v)
Sets the car of a list. l list. v the value.
Referenced by list_append, list_cons, list_pop, list_push.
void list_set_cdr(list *l, void *v)
Sets the cdr of a list. l list. v the value.
Referenced by list_append, list_cons, list_pop, list_push, list_remove, list_reverse.
int list_is_empty(list *l)
l a list. true if the parameter is empty
References list_car, list_cdr, list_is_null.
Referenced by config_get, list_array, list_cons, list_destroy_deep, list_filter, list_index_of_int, list_index_of_str, list_map, list_pop, list_push, list_reverse, list_size, read_config_servers, string_join.
int list_size(list *l)
size of list.
References list_car, list_cdr, list_is_empty.
Referenced by list_array, list_remove, list_reverse, read_config_servers, reader_function, reader_parse_poll_packet, reader_poll_loop.
list* list_cons(void *v, list *l)
a list formed of the given value cons-ed with the given list. Allocates memory. Returns NULL on failure.
References list_create, list_is_empty, list_is_null, list_set_car, list_set_cdr.
Referenced by list_append, list_filter, list_map.
list* list_map(list *l, void *(*fn)(void *))
Maps a function across all elements of a list a new list of the results, or NULL on failure
References list_car, list_cdr, list_cons, list_is_empty, null_list.
list* list_filter(list *l, int(*fn)(void *, void *), void *args)
Given a filtering function, l The list to filter. fn A function to apply to each element in the list. If the application is TRUE, then the element is retained, else it is not included in the new list. args Arguments to be passed to the filtering function. a new list consisting of elements of the old list that pass the test or NULL on failure.
References list_car, list_cdr, list_cons, list_destroy, list_is_empty, null_list.
list* list_copy(list *l)
list* list_reverse(list *l)
destructively modifies the current list. note, you must assign the result back in place, for this method is unable to modify in place, at the current time. the list reversed. pointer to new head.
References list_cdr, list_is_empty, list_set_cdr, list_size.
Referenced by string_split.
list* list_append(list *l, void *v)
Destructive. l A list. v A value to insert at the last position. The last element of the list now points to a new node containing v. The newly created end node, or NULL on failure.
References list_car, list_cdr, list_cons, list_set_car, list_set_cdr, null_list.
Referenced by config_get_all.
void* list_remove(list *l, int index)
Removes the element at the given index the value of the element removed, or NULL on failure.
References list_atom_destroy, list_car, list_cdr, list_nth_atom, list_pop, list_set_cdr, list_size.
Referenced by browse_callback.
void* list_simple_free_fn(void *v)
the following 3 functions conform to the function signatures accepted by list_map and list_filter
void* list_str_print_fn(void *)
void* list_int_print_fn(void *)
list* null_list()
a new empty list, or NULL on failure.
References list_create.
Referenced by list_append, list_filter, list_map.
list* list_push(list *l, void *v)
Alias of: l = list_cons(v, l); l A list to become the cdr. v A value to become the car. A list composed of v and l or NULL on failure
References list_car, list_cdr, list_create, list_is_empty, list_is_null, list_set_car, list_set_cdr.
Referenced by find_all_readers, read_config_servers, reader_parse_poll_packet, resolve_callback, string_split.
void* list_pop(list *l)
Destructive. Convenience function. Opposite of list_push(). l A list. The car of the old list. The list is now the cdr of the original list.
References list_atom_destroy, list_car, list_cdr, list_is_empty, list_is_null, list_set_car, list_set_cdr.
Referenced by config_get, list_remove, read_config_servers, reader_function, reader_poll_loop.
void* list_nth(list *l, int i)
the value at the nth position of the list. NULL on failure, however accessing past the end of the list is undefined.
References list_car, list_cdr, list_nth.
Referenced by list_nth, read_config_servers.
void** list_array(list *l)
a new array, filled with the contents of the provided list the list is NULL terminated, but since the values of the array may be NULL, this should not be used to determine the length of the array. rather, list_size() should be used. NULL on failure or empty list.
References list_car, list_cdr, list_is_empty, list_size.
int list_index_of_int(list *haystack, int needle)
index of first eleemnt encountered matching needle, ENOTFND otherwise.
References list_car, list_cdr, list_is_empty.
int list_index_of_str(list *haystack, const char *needle)
index of first eleemnt encountered matching needle, ENOTFND otherwise.
References list_car, list_cdr, list_is_empty.