reader.h
EDEVERR
Device error.
Referenced by reader_poll_loop.
BEEP
True.
Referenced by reader_function.
NOBEEP
False.
RFID1_VID
RFID1_PID
RFID1_DESC
RFID1_BAUDRATE
RFID1_PKT_PING
RFID1_PKT_AGCTGL
RFID1_PKT_AMPMTGL
RFID1_PKT_PASSBEEP
RFID1_PKT_FAILBEEP
RFID1_PKT_15693INVRQ
RFID1_PKT_TISIDPOLL
RFID1_PKT_MODEMEM
RFID1_PKT_MODEUID
RFID1_PKT_TAGIT
RFID1_EOP_CHAR
RFID_ID_LEN
ReturnCode
struct reader* reader_create()
Return a newly allocated reader.
Referenced by find_all_readers.
void reader_init(struct reader *reader, struct ftdi_context *ftdic, struct usb_device *dev)
Initialize a newly allocated reader.
Referenced by find_all_readers.
struct tag* tag_create()
Returns a newly allocated tag.
Referenced by reader_parse_poll_packet.
void tag_init(struct tag *tag, char *id, struct reader *parent)
Initializes a newly allocated tag.
References tag::parent.
Referenced by reader_parse_poll_packet.
list* find_all_readers(list *readers)
Returns a list of all connected readers.
readers Probably should be an empty list.
References list_push, reader_create, reader_init.
Referenced by reader_function.
ReturnCode reader_connect(struct reader *reader, int beep)
Connects to a given reader.
References reader_pass_beep, reader_ping, reader_purge, reader_reset.
Referenced by reader_function.
ReturnCode reader_disconnect(struct reader *reader)
Disconnects from a given reader.
ReturnCode reader_reset(struct reader *reader)
Resets a given reader.
Referenced by reader_connect.
ReturnCode reader_pass_beep(struct reader *reader)
Causes the reader to emit the PASS beep.
References reader_txPacketCheckAck.
Referenced by reader_connect.
ReturnCode reader_fail_beep(struct reader *reader)
Causes the reader to emit the FAIL beep.
References reader_txPacketCheckAck.
ReturnCode reader_ping(struct reader *reader)
Pings a given reader.
References reader_txPacketCheckAck.
Referenced by reader_connect.
ReturnCode reader_purge(struct reader *reader)
Purges a given reader.
Referenced by reader_connect, reader_poll15693, reader_pollTi.
int reader_read_packet(struct reader *r, char *buf, int maxlen)
Reads a packet from a reader into a buffer.
Referenced by reader_txPacketRxReply.
int reader_txPacketRxReply(struct reader *reader, char *tx_packet, int tx_packet_len, char *rx_buf, int rx_buf_len, int *payload_index)
TODO.
References reader_read_packet.
Referenced by reader_poll15693, reader_pollTi, reader_txPacketCheckAck.
ReturnCode reader_txPacketCheckAck(struct reader *reader, char *tx_packet, int tx_packet_len)
Returns if successfully acknowledged.
References reader_txPacketRxReply.
Referenced by reader_fail_beep, reader_pass_beep, reader_ping, reader_poll15693, reader_pollTi.
int reader_parse_poll_packet(struct reader *reader, struct list *tagList, char *packetPayload, int packetPayload_len)
Parses a packet returned from a reader poll.
References list_push, list_size, tag_create, tag_init.
Referenced by reader_poll15693, reader_pollTi.
int reader_poll15693(struct reader *reader, list *tagList)
Causes the reader to poll for and ISO15693 tag.
References reader_parse_poll_packet, reader_purge, reader_txPacketCheckAck, reader_txPacketRxReply.
Referenced by reader_poll_loop.
int reader_pollTi(struct reader *reader, list *tagList)
Attempts to poll the reader for various tags.
References reader_parse_poll_packet, reader_purge, reader_txPacketCheckAck, reader_txPacketRxReply.