.TH "reader" 3 "13 May 2010" "Version 1.0" "RFIDentify Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reader \- 
.PP
Completely identifies a currently connected RFID reader.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reader.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBconnected\fP"
.br
.ti -1c
.RI "struct ftdi_context * \fBftdic\fP"
.br
.ti -1c
.RI "struct usb_device * \fBdev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Completely identifies a currently connected RFID reader. 
.PP
Definition at line 67 of file reader.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for RFIDentify Client from the source code.
