.TH "tag" 3 "13 May 2010" "Version 1.0" "RFIDentify Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tag \- 
.PP
An RFID identification.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reader.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBid\fP"
.br
.ti -1c
.RI "struct \fBreader\fP * \fBparent\fP"
.br
.RI "\fIUnique ID. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An RFID identification. 
.PP
Definition at line 82 of file reader.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for RFIDentify Client from the source code.
